config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {registrations: 'users/registrations'}
  resources :users
  resources :profiles, only: [:show, :new, :edit, :create, :update]
  resources :reservations, only: [:index]
  resources :rooms do
    collection do
      get "search"
    end
  end
  resources :rooms do
    resources :reservations, except: :index
  end
  # get "room/search"
  root 'top#index'
end

app/views/shared/_error.html.erb
<% if obj.errors.any? %>
  <% obj.errors.full_messages.each do |message| %>
    <ul>
      <li><%= message %></p>
    </ul>
  <% end %>
<% end %>

app/views/shared/_header.html.erb
<nav class="navbar" style="background-color: black">
  <div class="navbar-header" style="padding: 10px;">
    <!-- left nav-->
    <div class="navbar-left" style="display: flex; align-items: center;">
      <div>
        <a href="">
          <%= link_to image_tag('rabbit.jpg', :height =>'40'),root_path %>
        </a>
      </div>
    </div>
    <!-- right nav -->
    <div class="navbar-right">
      <div class="navbar-sign-in">
        <% if user_signed_in? %>
          <strong>
            <div style="position: absolute; right: 260px; top: 12px; width: max-content;">
              <%= link_to current_user.name, root_path %>
            </div>
          </strong>
          <div style="position: absolute; right: 155px; top: 5px; width: max-content;">
            <%= link_to 'Log out', destroy_user_session_path, method: :delete, class: "btn btn-secondary nav-item" %>
          </div>
          <div class="nav_menu">
            <label for="menu_bar01">Menu</label>
            <input type="checkbox" id="menu_bar01" />
            <ul id="links01">
                <li><%= link_to "Register Room", new_room_path %></li>
                <li><%= link_to "Reservations", reservations_path %></li>
                <li><%= link_to "Rooms" , rooms_path %></li>
                <li><%= link_to "Setting", user_path(current_user.id) %></li>
            </ul>
          </div>
        <% else %>
          <div style="position: absolute; right: 90px; top: 5px; width: max-content;">
            <%= link_to("Sign up", new_user_registration_path, { class: "btn btn-primary" }) %>
          </div>
          <div style="position: absolute; right: 5px; top: 5px; width: max-content;">
            <%= link_to("Log in", new_user_session_path, { class: "btn btn-secondary"}) %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>
  

app/views/shared/_room-new-edit.html.erb
<%= form_with model: @room, local: true do |f| %>
  <div class="form_group">
    <%= f.label :Name %><br/>
    <%= f.text_field :name %>
  </div>
  <div class="form_group">
    <%= f.label :Introduction %><br/>
    <%= f.text_area :room_introduction %>
  </div>
  <div class="form_group">
    <%= f.label :Fee %><br/>
    <%= f.number_field :fee, min: "0" %><br>
  </div>
  <div class="form_group">
    <%= f.label :Address %><br/>
    <%= f.text_field :address %><br>
  </div>
  <div style="margin-top: 30px;">
    <%= f.attachment_field :image %><br/>
  </div>
  <div class="submit_block">
    <%= f.submit class: "button" %>
  </div>
<% end %>