config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {registrations: 'users/registrations'}
  resources :users
  resources :profiles, only: [:show, :new, :edit, :create, :update]
  resources :reservations, only: [:index]
  resources :rooms do
    collection do
      get "search"
    end
  end
  resources :rooms do
    resources :reservations, except: :index
  end
  # get "room/search"
  root 'top#index'
end

app/models/reservation.rb
class Reservation < ApplicationRecord
  belongs_to :user, dependent: :destroy
  belongs_to :room, dependent: :destroy
end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
  before_action :authenticate_user!
  before_action :find_reservation, only: [:show, :edit, :update, :destroy]

  def index
    @user = current_user
    @reservations = Reservation.where(user_id: current_user.id)
  end

  def new
    @reservation = Reservation.new(reservation_params)
    @user = current_user
    @reservation.user_id = current_user.id
    @room = Room.find(params[:room_id])
    @reservation.room_id = @room.id
    @reservation.room = @room
    @reservation.days = (@reservation.end_date - @reservation.start_date).to_i
    @reservation.total = @room.fee * @reservation.people * @reservation.days
  end
  
  def edit
  end

  def show
  end

  def create
    @reservation = Reservation.new(reservation_params)
    @user = current_user
    @reservation.user_id = current_user.id
    @room = Room.find(params[:room_id])
    @reservation.room_id = @room.id
    @reservation.room = @room
    @reservation.days = (@reservation.end_date - @reservation.start_date).to_i
    @reservation.total = @room.fee * @reservation.people * @reservation.days
    if @reservation.save
      redirect_to root_path, notice: "Succeeded!"
    else
      render :edit
    end
  end
  
  def update
    if @reservation.update(reservation_params)
      redirect_to room_reservation_path, notice: "Updated!"
    else
      render :edit
    end
  end
  
  def destroy
    if @reservation.destroy
      redirect_to root_path, notice: "Deleted."
    else
      redirect_to root_path, alert: "Failed..."
    end
  end
  
  private
  
  def reservation_params
    params.permit(:start_date, :end_date, :people, :room_id, :user_id)
  end

  def find_reservation
    @reservation = Reservation.find(params[:id])
  end
end

app/helpers/reservations_helper.rb
module ReservationsHelper
end

app/views/reservations/index.html.erb
<div class="container">
  <div class="table">
    <table>
      <thead>
        <tr>
          <th>Image</th>
          <th>Name</th>
          <th>Introduction</th>
          <th>Total fee</th>
          <th>Start date</th>
          <th>End date</th>
          <th>Reserved day</th>
        </tr>
      </thead>

      <tbody>
        <% @reservations.each do |reservation| %>
          <tr>
            <td><%= attachment_image_tag reservation.room, :image, format: 'jpeg', size: "150x100", fallback: "no_image.jpg" %></td>
            <td><%= link_to reservation.room.name, room_path(reservation.room.id) %></td>
            <td><%= reservation.room.room_introduction %></td>
            <td><%= reservation.total %></td>
            <td><%= reservation.start_date %></td>
            <td><%= reservation.end_date %></td>
            <td><%= reservation.created_at.strftime('%Y/%m/%d') %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/reservations/new.html.erb
<div class="container">
  <h2>Confirmation</h2>
  <%= form_with url: room_reservations_path(@reservation.room_id) do |f| %>
    <div class="form_group">
      <label>Fee:</label><br/>
      <%= @reservation.room.fee %> yen/Person/Day
    </div>
    <div class="form_group">
      <label>Start Day:</label><br/>
      <%= f.text_field :start_date, value: params[:start_date], :readonly => true %>
    </div>
    <div class="form_group">
      <label>End day:</label><br/>
      <%= f.text_field :end_date, value: params[:end_date], :readonly => true %>
    </div>
    <div class="form_group">
      <label>Lengt of stay:</label><br/>
      <%= @reservation.days %> night
    </div>
    <div class="form_group">
      <label>People:</label><br/>
      <%= f.number_field :people, value: params[:people], :readonly => true %>
    </div>
    <div class="form_group">
      <label>Total fee:</label><br/>
      <%= @reservation.total %> yen
    </div>
    <div class="submit_block">
      <%= f.submit "Complete" %>
    </div>
  <% end %>
  <div class="link">
    <%= link_to "Back", :back %>
  </div>
</div> 