config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {registrations: 'users/registrations'}
  resources :users
  resources :profiles, only: [:show, :new, :edit, :create, :update]
  resources :reservations, only: [:index]
  resources :rooms do
    collection do
      get "search"
    end
  end
  resources :rooms do
    resources :reservations, except: :index
  end
  # get "room/search"
  root 'top#index'
end

app/models/room.rb
class Room < ApplicationRecord
  attachment :image
  has_many :reservarions
  belongs_to :user, dependent: :destroy
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :find_room, only: [:show, :edit, :update, :destroy]
  
  def index
    @rooms = Room.all
  end
  
  def edit
  end

  def show
  end

  def new
    @room = Room.new
  end

  def create
    @room = Room.new(room_params)
    @room.user_id = current_user.id
    if @room.save
      redirect_to rooms_path, notice: "Succeeded!"
    else
      render :new
    end
  end
  
  def update
    @user = current_user
    @room.user_id = current_user.id
    if @room.update!(room_params)
      redirect_to rooms_path, notice: "Updated!"
    else
      render :edit
    end
  end
  
  def destroy
    if @room.destroy
      redirect_to root_path, notice: "Deleted."
    else
      redirect_to root_path, alert: "Failed..."
    end
  end
    
  private
  
  def room_params
    params.require(:room).permit(:name, :room_introduction, :fee, :address, :image, :user_id)
  end

  def find_room
    @room = Room.find(params[:id])
  end
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/rooms/edit.html.erb
<div class="container">
  <h2>Edit room</h2>
  <%= render 'shared/room-new-edit', room: @room %>
  <div class="link"><%= link_to "Back", rooms_path %></div>
</div>

app/views/rooms/index.html.erb
<div class="container">
  <h2>All rooms</h2>
  <div class="table">
    <table>
      <thead>
        <tr>
          <th>Image</th>
          <th>Name</th>
          <th>Introduction</th>
          <th>Fee</th>
          <th>Address</th>
          <th>Created date</th>
          <th>Edit</th>
        </tr>
      </thead>
      <tbody>
        <% @rooms.each do |room| %>
          <tr>
            <td>
              <%= attachment_image_tag room, :image, format: 'jpeg', size: "200x100", fallback: "no_image.jpg"%>
            </td>
            <td><%= link_to room.name, room_path(room.id) %></td>
            <td><%= room.room_introduction %></td>
            <td><%= room.fee %></td>
            <td><%= room.address %></td>
            <td><%= room.created_at.strftime('%Y/%m/%d') %></td>
            <td><%= link_to "Edit", [:edit, room] %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/rooms/new.html.erb
<div class="container">
  <h2>Resister room</h2>
  <%= render 'shared/room-new-edit' %>
</div>

app/views/rooms/search.html.erb
<div class="container">
  <h2>Results</h2>
  <div class="result">
    <% @results.each do |room| %>
    <div class="room_box">
      <%= link_to room_path(room.id) do %>
      <div class="room_image">
        <%= attachment_image_tag room, :image, format: 'jpeg', size: "200x120", fallback: "no_image.jpg" %>
      </div>
      <div class="room_overviews">
        <div class="room_overview form_group">
          <label>Name: </label>
          <%= link_to room.name, room_path(room.id) %>
        </div>
        <div class="room_overview form_group">
          <label>Fee: </label>
          <%= link_to room.fee, room_path(room.id) %> yen/day
        </div>
        <div class="room_overview form_group">
          <label>Address: </label>
          <%= link_to room.address, room_path(room.id) %>
        </div>
      </div>
      <% end %>  
    </div>
    <% end %>
  </div>
</div>

app/views/rooms/show.html.erb
<div class="container" style="display: flex">
  <!--Left: room information-->
  <div class="room_information">
    <div class="form_group">
      <label>Image</label><br/>
      <%= attachment_image_tag @room, :image, format: 'jpeg', size: "600x400", fallback: "no_image.jpg"%>
    </div>
    <div class="form_group">
      <label>Name</label><br/>
      <%= @room.name %>
    </div>
    <div class="form_group">
      <label>Address</label><br/>
      <%= @room.address %>
    </div>
    <div class="form_group">
      <label>Introduction</label><br/>
      <%= @room.room_introduction %>
    </div>
    <div class="link">
      <%= link_to "Back", :back %>
    </div>
  </div>
  <!--Right: reservation form-->
  <div class="reservation_form">
    <div class="field" style="font-size: 25px;">
      <%= @room.fee %> yen/day
    </div>
    <!--Reservation form-->
    <%= form_with url: new_room_reservation_path(@room), method: :get do |f| %>
    <div class="form_group">
      <%= f.label :Start_day %><br/>
      <%= f.date_field :start_date %><br>
    </div>
    <div class="form_group">
      <%= f.label :End_day %><br/>
      <%= f.date_field :end_date %>
    </div>
    <div class="form_group">
      <%= f.label :People %><br/>
      <%= f.number_field :people %>
    </div>
    <div class="submit_block">
      <%= f.submit class: "button" %>
    </div>
  <% end %> 
  </div>
</div>