config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {registrations: 'users/registrations'}
  resources :users
  resources :profiles, only: [:show, :new, :edit, :create, :update]
  resources :reservations, only: [:index]
  resources :rooms do
    collection do
      get "search"
    end
  end
  resources :rooms do
    resources :reservations, except: :index
  end
  # get "room/search"
  root 'top#index'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Myapp3</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application' %>
    <link href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" rel="stylesheet">
  </head>

  <body>
    <div>
      <%= render 'shared/header' %>
      <div class="header-search">
        <div class="search-box">
          <div class="search_1">
            <i class="fas fa-map-marker-alt"></i>
            <%= search_form_for @q, url: search_rooms_path do |f| %>
              <%= f.search_field :address_cont, placeholder: 'Area' %>
            <% end %>
          </div>
          <div class="search_2">
            <i class="fas fa-search"></i>
            <%= search_form_for @q, url: search_rooms_path do |f| %>
              <%= f.search_field :address_or_name_or_room_introduction_cont, placeholder: 'Key word' %>
            <% end %>
          </div>
        </div>
      </div>
      <!--login message-->
      <div class="notifications">
          <p class="notice"><%= notice %></p>
          <p class="alert"><%= alert %></p>
      </div>
    </div>
    <%= yield %>
    <footer class="footer">
      <p>© 2021 Mika</p>
    </footer>
  </body>
</html>